<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Angsuran Kontrak Aktif</name>
   <tag></tag>
   <elementGuidId>848b20c5-a4f7-4de2-b89f-0168ea45239f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtAngsuranKontrakAktif']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtAngsuranKontrakAktif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63e858dc-5910-4199-887f-de6d65c2ea12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtAngsuranKontrakAktif</value>
      <webElementGuid>5dba54f8-b7da-44c7-a8b2-67fca9fd1267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dcb8dbbd-3f0d-4e8d-91b7-30411454c287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4296329b-8986-434a-80ea-8553ab06e965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$txtAngsuranKontrakAktif\',\'\')', 0)</value>
      <webElementGuid>c94a4c5b-30d0-41e4-a550-b55e90f31445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return isnumerickey(event);</value>
      <webElementGuid>405f7be3-05c1-41df-906a-537184abb3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtAngsuranKontrakAktif</value>
      <webElementGuid>f5eb519c-52c0-4193-996f-e270f14b32bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>594e691c-24e6-41a9-9b4f-cfd04d850b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8b128dd0-7fa4-4d01-937d-d732ab48d8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>FormatCurrency(this)</value>
      <webElementGuid>06ab29d6-65f5-48b2-87b0-a7e0fac2ded3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1.000.xxx</value>
      <webElementGuid>6d40752f-e430-439d-b03f-057a030eb135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtAngsuranKontrakAktif&quot;)</value>
      <webElementGuid>1af49df3-b533-4b34-abea-88a9dc60c340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtAngsuranKontrakAktif']</value>
      <webElementGuid>c8576e99-9994-4ae7-a823-db8e98f69472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabcapacity']/div[4]/div/div/div[2]/div/input[2]</value>
      <webElementGuid>fd12fa8f-2f5a-4c2a-be3f-306aad7e7d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/input[2]</value>
      <webElementGuid>9dcb1237-5b6f-4e3b-9d66-56123e12b64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtAngsuranKontrakAktif' and @type = 'text' and @id = 'main_txtAngsuranKontrakAktif' and @placeholder = '1.000.xxx']</value>
      <webElementGuid>f6123457-6c62-4830-a52a-638d899c2b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
