<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pendapatan Perbulan</name>
   <tag></tag>
   <elementGuidId>099c7508-cd15-478a-abd2-4aeaa9addf2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'main_txtPendapatanPerbulan']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtPendapatanPerbulan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtPendapatanPerbulan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ee0ea99-e6ca-42fc-9f02-54e153c2d20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtPendapatanPerbulan</value>
      <webElementGuid>0167b8a4-2751-4362-8792-5a8c556b7ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30b57d9d-66f5-4c57-a1af-dbfd00dd9f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d511df6f-4767-4375-8eb2-8914c3752c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$txtPendapatanPerbulan\',\'\')', 0)</value>
      <webElementGuid>b561ed59-88e8-42d4-bb03-953bbaffaa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return isnumerickey(event);</value>
      <webElementGuid>b9c5fcc9-f051-4fdd-ae1a-bc20d77c1521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtPendapatanPerbulan</value>
      <webElementGuid>200c5df0-a2d9-4edf-93fd-c70491a68d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4b0acf3-fd2c-4761-a95f-fb531e005bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0146bd12-5971-4a98-935b-29095811e5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>FormatCurrency(this)</value>
      <webElementGuid>e15af7ab-30e7-4fea-a9fb-514b33bb8587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1.000.xxx</value>
      <webElementGuid>f6f87419-97be-4b85-94c2-0e3da6df8602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtPendapatanPerbulan&quot;)</value>
      <webElementGuid>1e4a3953-61dd-4c81-85ad-28507bc579a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtPendapatanPerbulan']</value>
      <webElementGuid>469c2f84-6149-495e-9474-dd6cb7601667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabcapacity']/div[4]/div/div/div/div/input</value>
      <webElementGuid>48ed9fbb-46a4-4a8f-92e9-5b15b0483745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/div/div/input</value>
      <webElementGuid>98a552f9-77eb-4c1e-a654-f2f13b3ecb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtPendapatanPerbulan' and @type = 'text' and @id = 'main_txtPendapatanPerbulan' and @placeholder = '1.000.xxx']</value>
      <webElementGuid>d67ab06c-f06a-4699-b534-e5013b331af9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
