<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tipe Industri</name>
   <tag></tag>
   <elementGuidId>db4cce62-c9ff-4a44-9712-f0534091b4d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-main_ddlTipeIndustri-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-main_ddlTipeIndustri-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4bcc8127-f5c8-47eb-b954-92d78778a699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>53d36747-feb3-48fe-b76c-2bbb0a424104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-main_ddlTipeIndustri-container</value>
      <webElementGuid>b780ca9f-50f2-42cd-8857-28ea6d167e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>05b3d37a-fb9e-44df-a9f6-eb1af8689f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72e5fd33-62d6-42d1-bd59-8e92f733f83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select One</value>
      <webElementGuid>ea1078b6-d01d-407a-9f33-6db9b5e4bbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select One</value>
      <webElementGuid>5210d4e4-c909-4bb7-9d2b-634fe2177040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-main_ddlTipeIndustri-container&quot;)</value>
      <webElementGuid>3810020a-59a9-4977-8168-cb675fcf5fd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-main_ddlTipeIndustri-container']</value>
      <webElementGuid>c5da6fa1-bd0d-4418-a843-dde67f7f15e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabcapacity']/div[5]/div/div/div[3]/div/span/span/span/span</value>
      <webElementGuid>c07f6d69-a044-4aed-9761-b9e28a95c764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Industri'])[1]/following::span[4]</value>
      <webElementGuid>92d5d9b4-ea8c-4267-8dbf-e38a52c5ab64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Bukti Kapasitas Pasangan'])[1]/following::span[4]</value>
      <webElementGuid>f4544c04-209c-4f89-9783-0716af31ad4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SRA'])[1]/preceding::span[3]</value>
      <webElementGuid>1f955601-b981-4727-b54c-2661a99da581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lama Kerja/Usaha (Tahun)'])[1]/preceding::span[3]</value>
      <webElementGuid>aa0daca2-10c6-45a2-934f-775054d13f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>bc254a6e-d7ac-4c6a-86f6-2e2547d42f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-main_ddlTipeIndustri-container' and @title = 'Select One' and (text() = 'Select One' or . = 'Select One')]</value>
      <webElementGuid>f20369fb-b474-44aa-8622-7f2586455842</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
