<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Recomendation</name>
   <tag></tag>
   <elementGuidId>4d8d7652-df07-4896-879e-7038cafd2b87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_btnRecomendation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_btnRecomendation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>317d5f87-c0cc-4254-b180-876107bfd6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_btnRecomendation</value>
      <webElementGuid>3cd4df97-ddf8-4011-b952-97dc370b4d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>7056c4a2-5f8c-4493-ac5b-77a75e05288b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$main$btnRecomendation','')</value>
      <webElementGuid>7695fab8-55ba-45a3-88e5-a18df9844e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recomendation</value>
      <webElementGuid>6ced5e85-8613-4683-86d4-833a48b4fcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_btnRecomendation&quot;)</value>
      <webElementGuid>c4e49486-b1ac-45cf-8557-8963bcc7a3b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='main_btnRecomendation']</value>
      <webElementGuid>c580f616-8e9f-4179-81f0-91151f833053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tab']/li[6]/a[2]</value>
      <webElementGuid>b0a6ffd8-48db-44d4-962e-3524691ffd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Recomendation')]</value>
      <webElementGuid>b3aab357-8160-4cc8-86f1-670ad7b3f20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/following::a[2]</value>
      <webElementGuid>1fb47c3c-1670-4732-94a6-d40f4d30e92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capital Collateral'])[1]/following::a[4]</value>
      <webElementGuid>20fab7e3-5fca-4ceb-abfd-3a470b04e890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deviasi'])[1]/preceding::a[2]</value>
      <webElementGuid>fb03c721-3824-48ce-a45a-184db7316614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek Google'])[1]/preceding::a[3]</value>
      <webElementGuid>e955e72b-c680-49bf-9864-f0000331846f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recomendation']/parent::*</value>
      <webElementGuid>9f9cbdc9-a61c-4e63-8c31-a55f2ba17349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$main$btnRecomendation','')&quot;)]</value>
      <webElementGuid>abaec7e1-9f11-4aa9-99b2-bc31ffc3835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a[2]</value>
      <webElementGuid>5c0cc4e2-a2b2-4f02-8b5d-0cab036a88f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'main_btnRecomendation' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$main$btnRecomendation&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Recomendation' or . = 'Recomendation')]</value>
      <webElementGuid>ecffc1eb-4e80-449c-b465-e495a91e23ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
