<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eye</name>
   <tag></tag>
   <elementGuidId>46e805ac-bce5-4b3e-a508-d3c2980a482d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lvList_ctrl0_linkView_0']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-eye</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4de8f124-3e6c-4fcf-a39f-c213b378b143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>d2f2c0e3-971b-481c-934d-f7e3d69b3c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_lvList_ctrl0_linkView_0&quot;)/i[@class=&quot;fa fa-eye&quot;]</value>
      <webElementGuid>f6995b74-66bb-4e5c-a13a-d6e5adcf3bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_lvList_ctrl0_linkView_0']/i</value>
      <webElementGuid>53d6553f-6296-43ed-b580-c76ea4b0467d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/a[2]/i</value>
      <webElementGuid>8b69cdca-a232-4365-8b5f-a5cd06f16fda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
