<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save</name>
   <tag></tag>
   <elementGuidId>df81576b-a71f-4ff7-912e-5972ceac483b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lbSaveRecommendation']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_lbSaveRecommendation > i.fas.fa-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8c1e1c0e-2e2c-4979-9a4c-194e0225c9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-save</value>
      <webElementGuid>82f1b5e3-a6a4-4614-abbd-0474bb1c27f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_lbSaveRecommendation&quot;)/i[@class=&quot;fas fa-save&quot;]</value>
      <webElementGuid>d6d7d109-c3f4-4783-a725-6f05f2df7e7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_lbSaveRecommendation']/i</value>
      <webElementGuid>20988ed4-d8d1-431a-b486-4f353ef255a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/a/i</value>
      <webElementGuid>0497b960-d11c-41db-a996-a1525fb19740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
