<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save</name>
   <tag></tag>
   <elementGuidId>fa458c80-bfb0-42a7-ac03-459543fa3eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lbSubmit']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_lbSubmit > i.fas.fa-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9c1b914a-70db-467d-ab30-1e78b12d13d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-save</value>
      <webElementGuid>3fa1f3ef-27b8-402e-9ff3-81bd4e93f39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_lbSubmit&quot;)/i[@class=&quot;fas fa-save&quot;]</value>
      <webElementGuid>360f6479-81ed-496d-b73e-f14b6cbd79aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_lbSubmit']/i</value>
      <webElementGuid>32410943-0cfb-4829-8cb3-c7270c4166a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/a/i</value>
      <webElementGuid>5ca7db7d-c286-4acb-bc4e-6181c0556ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
