<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Deviasi</name>
   <tag></tag>
   <elementGuidId>3d27593c-a8d8-4340-ae33-e87db5e93ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_btnCapital</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_btnDeviasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f418bb96-3da4-4736-a7e1-d96fcf7e7ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_btnCapital</value>
      <webElementGuid>d7c1ebc3-c1ec-4c8f-a079-4db1dd428428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>bdd7fff7-dc0d-4fd8-be17-ad5fcf696764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$main$btnCapital','')</value>
      <webElementGuid>b62e9b53-c4fa-4c89-8619-249b161968d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Capital Collateral</value>
      <webElementGuid>71de8cb2-a1cd-4f08-979c-a7ebcf84e228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_btnCapital&quot;)</value>
      <webElementGuid>fc02985c-78f9-454c-8203-bd65d924cb56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='main_btnCapital']</value>
      <webElementGuid>8b530cbb-9c04-4a6d-acf5-abbafb02cbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tab']/li[4]/a[2]</value>
      <webElementGuid>77918ca0-a86c-4f88-8540-805369b751ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Capital Collateral')]</value>
      <webElementGuid>04d01e6b-b220-4b3a-9229-6384e26db1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condition Capacity'])[1]/following::a[2]</value>
      <webElementGuid>df3ef17f-71e8-44e9-9ee1-f2ac82c7877c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purpose Caracter'])[1]/following::a[4]</value>
      <webElementGuid>69ed96d9-e59d-47d1-a244-2a8220076669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/preceding::a[2]</value>
      <webElementGuid>b6907b47-1b97-4dbe-b7a1-5f42d68aaa26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recomendation'])[1]/preceding::a[4]</value>
      <webElementGuid>87fb59f8-0dc2-4019-85b6-461b2f6f293b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Capital Collateral']/parent::*</value>
      <webElementGuid>176c18d3-6c0b-451d-ad14-c91dcb09e543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$main$btnCapital','')&quot;)]</value>
      <webElementGuid>72888056-173f-42e7-a0ce-d0dec94faf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a[2]</value>
      <webElementGuid>3347fed4-8e3b-4a82-8083-0091789dc735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'main_btnCapital' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$main$btnCapital&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Capital Collateral' or . = 'Capital Collateral')]</value>
      <webElementGuid>79d890da-e00f-40a4-be90-de6986f327a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
