<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daily Monitoring CA</name>
   <tag></tag>
   <elementGuidId>f5cc75ce-af17-4217-a827-adcf3f2ccb70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c862bf3-7ec8-4a63-8b51-26389820728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>e51cd01e-3134-4e9b-a317-337f245603b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/ecaw-retail/MonitoringDaily.aspx</value>
      <webElementGuid>fce4a2a7-91d2-407f-84a2-5ff401b6658e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t2</value>
      <webElementGuid>a05b2199-a521-4261-b76c-c32788b61bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daily Monitoring CA</value>
      <webElementGuid>e0cb68b9-cd29-44c3-a69d-9b4541af269b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t2&quot;)</value>
      <webElementGuid>432b378d-5a40-41d9-952c-4985852dcf89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t2']</value>
      <webElementGuid>9dca4677-24b7-4d9f-9bed-e0b1d85c6a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1']/table[3]/tbody/tr/td[2]/a</value>
      <webElementGuid>d17aef55-5bb3-4aae-bf63-a5dec785d04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daily Monitoring CA')]</value>
      <webElementGuid>2240765a-a00b-432f-8ba2-8672268ca0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Analyst Review'])[1]/following::a[1]</value>
      <webElementGuid>ec942b66-ea6b-46be-ba44-449673e3775a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Deviasi'])[1]/following::a[2]</value>
      <webElementGuid>a03537c1-a80c-41df-b9ff-6f65cae32e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval List'])[1]/preceding::a[2]</value>
      <webElementGuid>541febc2-0505-4897-ab93-50c6f1ff900b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PURCHASE ORDER'])[1]/preceding::a[2]</value>
      <webElementGuid>71c62b66-ffea-4a5f-81de-50c2dd9c883d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daily Monitoring CA']/parent::*</value>
      <webElementGuid>cee5182e-3e74-4d3a-a28e-a1f1839beca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/ecaw-retail/MonitoringDaily.aspx')]</value>
      <webElementGuid>8453641a-98b6-4477-9f4a-b1ec59340216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[2]/a</value>
      <webElementGuid>ca9b7039-4abd-42b7-9f38-9b9447732802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/ecaw-retail/MonitoringDaily.aspx' and @id = 'TreeView1t2' and (text() = 'Daily Monitoring CA' or . = 'Daily Monitoring CA')]</value>
      <webElementGuid>0b22f6ed-60e7-446f-96e4-5cd7c9f5d364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
