<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save</name>
   <tag></tag>
   <elementGuidId>77f1b5c7-eaf4-470b-9619-2ce2d71a3b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_lbSubmit > i.fas.fa-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lbSubmit']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a831b709-8092-4ffd-850d-3f7c02c67f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-save</value>
      <webElementGuid>a33eed0f-c9aa-4530-b2a4-4a0074b07cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_lbSubmit&quot;)/i[@class=&quot;fas fa-save&quot;]</value>
      <webElementGuid>0eaa9556-f4ff-40bc-a765-12f435db4afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_lbSubmit']/i</value>
      <webElementGuid>2da66bed-99c0-425c-b47d-4f64ddec983f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/a/i</value>
      <webElementGuid>aefd9506-7706-4167-84af-89e4ee99a038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
