<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Credit Analyst-DDL</name>
   <tag></tag>
   <elementGuidId>f62731d9-3d0d-45a1-9ca3-296e6fbe7de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='main_ddlRejectApr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_ddlRejectApr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e05765a1-1858-4f31-ad3b-269aa3dc859f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$ddlRejectApr</value>
      <webElementGuid>3fd3abe1-72b6-40fb-83e3-bb43bea1a364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$ddlRejectApr\',\'\')', 0)</value>
      <webElementGuid>51947825-da06-4f0d-8f85-00bce3e84f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_ddlRejectApr</value>
      <webElementGuid>48fcac94-5e2d-40e1-91c9-123d401f3673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>276c3b1c-159d-455e-a54b-9f9d139b9fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Select One
	Approve
	Reject

</value>
      <webElementGuid>cdd9818d-e7c0-4b0a-8f92-be131aa2a048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_ddlRejectApr&quot;)</value>
      <webElementGuid>b2f3638d-9205-4c9e-9a4f-cc4186baa3f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='main_ddlRejectApr']</value>
      <webElementGuid>a2dec2c8-53ff-4f12-b33b-86ba0edb96bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabrecomendation']/div[6]/div/select</value>
      <webElementGuid>05b53057-51f6-4ef0-89ef-4d10ef36fbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>2c9a88f1-7682-4625-8ca4-cd624d7efe9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>8f0e8c4d-af38-4d4f-b55c-1d2cc094c5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>d2873181-fe25-46d1-8a4c-7beb06d5b9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$main$ddlRejectApr' and @id = 'main_ddlRejectApr' and (text() = '
	Select One
	Approve
	Reject

' or . = '
	Select One
	Approve
	Reject

')]</value>
      <webElementGuid>4cd5ad02-f574-4f0d-a8ef-c2d3eb7a8358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
