<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cek Google</name>
   <tag></tag>
   <elementGuidId>0e140e81-42b3-4c74-bf99-5813da7074d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabinformation']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.note-editor.note-frame.card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a28730b-5bca-4be8-8790-84b668517c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editor note-frame card</value>
      <webElementGuid>d1112173-2aa0-4a70-9dcb-d945a56a47ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NormalBlockquoteCodeHeader 1Header 2Header 3Header 4Header 5Header 6Lucida Sans Arial Arial Black Comic Sans MS Courier New Helvetica Impact Tahoma Times New Roman Verdana Lucida Sans Lucida Sans Regular Lucida Sans UnicodeBackground ColorTransparentSelectText ColorReset to defaultSelect1 x 1Insert Link×Text to displayTo what URL should this link go? Open in new window Use default protocol Insert Image×Select from filesImage URL100%50%25%Insert Video×Video URL (YouTube, Vimeo, Vine, Instagram, DailyMotion or Youku)Help×ESCEscapeENTERInsert ParagraphCTRL+ZUndo the last commandCTRL+YRedo the last commandTABTabSHIFT+TABUntabCTRL+BSet a bold styleCTRL+ISet a italic styleCTRL+USet a underline styleCTRL+SHIFT+SSet a strikethrough styleCTRL+BACKSLASHClean a styleCTRL+SHIFT+LSet left alignCTRL+SHIFT+ESet center alignCTRL+SHIFT+RSet right alignCTRL+SHIFT+JSet full alignCTRL+SHIFT+NUM7Toggle unordered listCTRL+SHIFT+NUM8Toggle ordered listCTRL+LEFTBRACKETOutdent on current paragraphCTRL+RIGHTBRACKETIndent on current paragraphCTRL+NUM0Change current block's format as a paragraph(P tag)CTRL+NUM1Change current block's format as H1CTRL+NUM2Change current block's format as H2CTRL+NUM3Change current block's format as H3CTRL+NUM4Change current block's format as H4CTRL+NUM5Change current block's format as H5CTRL+NUM6Change current block's format as H6CTRL+ENTERInsert horizontal ruleCTRL+KShow Link DialogSummernote 0.8.18 · Project · Issues</value>
      <webElementGuid>167d1534-4953-4474-9f2a-0ed503b10572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabinformation&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;note-editor note-frame card&quot;]</value>
      <webElementGuid>cd362318-d3c1-45e7-9762-137a6c508329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabinformation']/div/div/div/div</value>
      <webElementGuid>6216f758-f3a2-4aa2-b06e-1d2f31867b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek Google'])[1]/following::div[1]</value>
      <webElementGuid>1ea3a44b-3ee1-43fa-86c6-4d5963b0f74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deviasi'])[1]/following::div[7]</value>
      <webElementGuid>ef1673cc-d199-4397-b7ef-7affe356ae9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>4c51d9c7-fd6a-4cc6-ac66-d3cf8fda4177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;NormalBlockquoteCodeHeader 1Header 2Header 3Header 4Header 5Header 6Lucida Sans Arial Arial Black Comic Sans MS Courier New Helvetica Impact Tahoma Times New Roman Verdana Lucida Sans Lucida Sans Regular Lucida Sans UnicodeBackground ColorTransparentSelectText ColorReset to defaultSelect1 x 1Insert Link×Text to displayTo what URL should this link go? Open in new window Use default protocol Insert Image×Select from filesImage URL100%50%25%Insert Video×Video URL (YouTube, Vimeo, Vine, Instagram, DailyMotion or Youku)Help×ESCEscapeENTERInsert ParagraphCTRL+ZUndo the last commandCTRL+YRedo the last commandTABTabSHIFT+TABUntabCTRL+BSet a bold styleCTRL+ISet a italic styleCTRL+USet a underline styleCTRL+SHIFT+SSet a strikethrough styleCTRL+BACKSLASHClean a styleCTRL+SHIFT+LSet left alignCTRL+SHIFT+ESet center alignCTRL+SHIFT+RSet right alignCTRL+SHIFT+JSet full alignCTRL+SHIFT+NUM7Toggle unordered listCTRL+SHIFT+NUM8Toggle ordered listCTRL+LEFTBRACKETOutdent on current paragraphCTRL+RIGHTBRACKETIndent on current paragraphCTRL+NUM0Change current block&quot; , &quot;'&quot; , &quot;s format as a paragraph(P tag)CTRL+NUM1Change current block&quot; , &quot;'&quot; , &quot;s format as H1CTRL+NUM2Change current block&quot; , &quot;'&quot; , &quot;s format as H2CTRL+NUM3Change current block&quot; , &quot;'&quot; , &quot;s format as H3CTRL+NUM4Change current block&quot; , &quot;'&quot; , &quot;s format as H4CTRL+NUM5Change current block&quot; , &quot;'&quot; , &quot;s format as H5CTRL+NUM6Change current block&quot; , &quot;'&quot; , &quot;s format as H6CTRL+ENTERInsert horizontal ruleCTRL+KShow Link DialogSummernote 0.8.18 · Project · Issues&quot;) or . = concat(&quot;NormalBlockquoteCodeHeader 1Header 2Header 3Header 4Header 5Header 6Lucida Sans Arial Arial Black Comic Sans MS Courier New Helvetica Impact Tahoma Times New Roman Verdana Lucida Sans Lucida Sans Regular Lucida Sans UnicodeBackground ColorTransparentSelectText ColorReset to defaultSelect1 x 1Insert Link×Text to displayTo what URL should this link go? Open in new window Use default protocol Insert Image×Select from filesImage URL100%50%25%Insert Video×Video URL (YouTube, Vimeo, Vine, Instagram, DailyMotion or Youku)Help×ESCEscapeENTERInsert ParagraphCTRL+ZUndo the last commandCTRL+YRedo the last commandTABTabSHIFT+TABUntabCTRL+BSet a bold styleCTRL+ISet a italic styleCTRL+USet a underline styleCTRL+SHIFT+SSet a strikethrough styleCTRL+BACKSLASHClean a styleCTRL+SHIFT+LSet left alignCTRL+SHIFT+ESet center alignCTRL+SHIFT+RSet right alignCTRL+SHIFT+JSet full alignCTRL+SHIFT+NUM7Toggle unordered listCTRL+SHIFT+NUM8Toggle ordered listCTRL+LEFTBRACKETOutdent on current paragraphCTRL+RIGHTBRACKETIndent on current paragraphCTRL+NUM0Change current block&quot; , &quot;'&quot; , &quot;s format as a paragraph(P tag)CTRL+NUM1Change current block&quot; , &quot;'&quot; , &quot;s format as H1CTRL+NUM2Change current block&quot; , &quot;'&quot; , &quot;s format as H2CTRL+NUM3Change current block&quot; , &quot;'&quot; , &quot;s format as H3CTRL+NUM4Change current block&quot; , &quot;'&quot; , &quot;s format as H4CTRL+NUM5Change current block&quot; , &quot;'&quot; , &quot;s format as H5CTRL+NUM6Change current block&quot; , &quot;'&quot; , &quot;s format as H6CTRL+ENTERInsert horizontal ruleCTRL+KShow Link DialogSummernote 0.8.18 · Project · Issues&quot;))]</value>
      <webElementGuid>91829769-89da-4bd4-b220-ac806fadf443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
