<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Purpose Caracter</name>
   <tag></tag>
   <elementGuidId>e1d79c51-3ce6-4faa-8361-bf0e4c0e6fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_btnPurpose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_btnPurpose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e8c384e-3b0d-42b2-babc-11e256523794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_btnPurpose</value>
      <webElementGuid>87105363-1cab-4ade-be39-874a411e57d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>7d7e076a-20a4-4ce9-a94b-676142ae923d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$main$btnPurpose','')</value>
      <webElementGuid>8ad648d0-78f8-4c73-b8b7-4ad45f5c4382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purpose Caracter</value>
      <webElementGuid>5009d830-1545-451c-8359-6d29df10fd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_btnPurpose&quot;)</value>
      <webElementGuid>006443a3-f5b7-4ed4-b616-dea2bc1ee9c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='main_btnPurpose']</value>
      <webElementGuid>46612766-60f0-4216-9100-ab7238748091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tab']/li[2]/a[2]</value>
      <webElementGuid>a97d2a37-3ffc-4d41-83d6-9c92cd44a93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Purpose Caracter')]</value>
      <webElementGuid>4e38b465-a4fe-4461-b3f7-19ba1c4ac9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Information'])[1]/following::a[2]</value>
      <webElementGuid>3d895468-c91d-449e-a30d-0d8445284ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QOSHIRIN'])[1]/following::a[4]</value>
      <webElementGuid>81366300-0793-4555-b842-e008fec71ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condition Capacity'])[1]/preceding::a[2]</value>
      <webElementGuid>cd908f6e-b873-44f9-a75e-0d951b9cbd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capital Collateral'])[1]/preceding::a[4]</value>
      <webElementGuid>54ce0bc7-420d-41b7-a761-7f7ccbb09314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purpose Caracter']/parent::*</value>
      <webElementGuid>db76fe1b-2b5d-4ab4-96a4-d354713b3fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$main$btnPurpose','')&quot;)]</value>
      <webElementGuid>a6a41600-835a-4ce1-a4f2-6affdc7c33d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]</value>
      <webElementGuid>7e18a927-d458-49ed-8097-81d8c94559c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'main_btnPurpose' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$main$btnPurpose&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Purpose Caracter' or . = 'Purpose Caracter')]</value>
      <webElementGuid>c99825eb-be61-46be-8d8e-4bdd5fc43514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
