<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save</name>
   <tag></tag>
   <elementGuidId>e5da8129-e6e4-4ad4-9c7a-888698e2074a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_btnSimpanInformation']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3ee82c8d-4167-4ddd-89ed-be4e61bc6dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-save</value>
      <webElementGuid>fc22dc00-0700-40d6-a551-cdf3c123842e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_btnSimpanInformation&quot;)/i[@class=&quot;fas fa-save&quot;]</value>
      <webElementGuid>34ed3ebc-29f1-4fcb-84a6-94a36cceb30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='main_btnSimpanInformation']/i</value>
      <webElementGuid>17c05915-da7b-42b6-8178-a4f9e7e05935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a/i</value>
      <webElementGuid>0d1b80c7-1649-444a-9e82-3952d0fd69e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
